### ISSUE TITLE
Handle dead shells more gracefully

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoEngine#18]
```
StartNewRound failed: Kein Prozess ist am anderen Ende der Pipe (System.IO.IOException)
   at System.ConsolePal.WindowsConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at EnoEngine.Game.CTF.InsertPutNewFlagsTasks(Int64 roundId, DateTime begin) in C:\\Users\\Benni\\repositories\\EnoEngine\\EnoEngine\\CTF.cs:line 115
   at EnoEngine.Game.CTF.<>c__DisplayClass5_1.<<StartNewRound>b__0>d.MoveNext() in C:\\Users\\Benni\\repositories\\EnoEngine\\EnoEngine\\CTF.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at EnoEngine.Game.CTF.StartNewRound() in C:\\Users\\Benni\\repositories\\EnoEngine\\EnoEngine\\CTF.cs:line 67
```

**Comment by Trolldemorted** [comment]
Shells should not die.
