### ISSUE TITLE
Socket disposal prints warning on shutdown

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoEngine#22]
Harmless, but annoying:

```
warn: EnoEngine.EnoEngine[0]
      RunProductionEndpoint failed to handle connection: Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'. (System.ObjectDisposedException)
         at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
         at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
         at System.Net.Sockets.TcpListener.<>c.<AcceptTcpClientAsync>b__28_1(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at EnoEngine.FlagSubmission.FlagSubmissionEndpoint.RunProductionEndpoint() in /services/EnoEngine/EnoEngine/FlagSubmissionEndpoint.cs:line 87
```

**Comment by Trolldemorted** [comment]
Fixed in #173
