### ISSUE TITLE
Handle invalid submission connections more gracefully

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoEngine#24]
```
warn: EnoEngine.EnoEngine[0]
      RunProductionEndpoint failed to handle connection: Enumerator failed to MoveNextAsync. (System.InvalidOperationException)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at EnoCore.EnoDatabase.GetTeamIdByPrefix(String attackerPrefixString) in /services/EnoEngine/EnoCore/EnoDatabase.cs:line 746
         at EnoEngine.FlagSubmission.FlagSubmissionEndpoint.RunProductionEndpoint() in /services/EnoEngine/EnoEngine/FlagSubmissionEndpoint.cs:line 99
```

We should send an error message and close the socket.

**Comment by Savallator** [comment]
This changed in the rewrite of the Submission for sure...
