### ISSUE TITLE
Resolve "The response ended prematurely" errors

### ISSUE THREAD

**Issue by ldruschk** [enowars/EnoEngine#46]
```
LaunchCheckerTask failed: An error occurred while sending the request. (System.Net.Http.HttpRequestException)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at EnoLauncher.Program.LaunchCheckerTask(CheckerTask task) in /services/EnoEngine/EnoLauncher/Program.cs:line 109
InnerException:
The response ended prematurely. (System.IO.IOException)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```

After some debugging I have come to the following conclusion:
* The issue occurs when the server closes a TCP connection for which Keep-Alive was enabled while a request from the EnoEngine is in-flight.
* To the EnoEngine it appears that the server closed the connection after receiving the request but before sending a response.
* The issue appears more often when the latency between EnoEngine and Checkers is high. The latency is the window in which the request and connection tear-down can overlap, when the latency is <1ms this is very unlikely to happen, with >300ms there is a realistic chance of this happening.
* This cannot be resolved by the checker since there is no way to know whether a new request is being sent while closing the connection. Increasing the timeout reduces the chances of this happening (since the client usually sends new requests quite soon). It does not eliminate the risk and may lead to resource exhaustion on the checker though.
* This can be resolved by the EnoEngine either by disabling Keep-Alive completely or dealing with the issue gracefully.

**Comment by Trolldemorted** [comment]
Why is only enochecker affected? Our tornado and kestrel based checkers are not 🤔

**Comment by ldruschk** [comment]
Because those use higher default connection timeouts I assume. Although I would say this issue is completely unrelated to the issue we saw with uwsgi before switching to gunicorn

**Comment by ldruschk** [comment]
We have temporarily worked around this issue by increasing the timeout to 1h in gunicorn, but this still seems like something that should be fixed on the Engine side since this issue might re-appear with any new checker implementation (although there hopefully won't be as many)
