### ISSUE TITLE
Prod flagsub endpoint should return an error message if it fails to determine the team

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoEngine#50]
Right now it logs `RunProductionEndpoint failed to handle connection: Enumerator failed to MoveNextAsync. (System.InvalidOperationException)` because `GetTeamIdByPrefix` throws.

**Comment by Trolldemorted** [comment]
@mauricesvp since you ran into this yesterday you might want to address it before the next test ctf

**Comment by Trolldemorted** [comment]
```
warn: EnoEngine.FlagSubmission.FlagSubmissionEndpoint[0]
      RunProductionEndpoint failed to handle connection: Enumerator failed to MoveNextAsync. (System.InvalidOperationException)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at EnoDatabase.EnoDatabase.GetTeamIdByPrefix(String attackerPrefixString) in /services/EnoEngine/EnoDatabase/EnoDatabase.cs:line 748
         at EnoEngine.FlagSubmission.FlagSubmissionEndpoint.RunProductionEndpoint(JsonConfiguration config, CancellationToken token) in /services/EnoEngine/EnoEngine/FlagSubmissionEndpoint.cs:line 236
```

**Comment by Trolldemorted** [comment]
was done for enowars4, it now returns a InvalidSenderError
